name: bgc_md2_env
channels: 
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab=2
  - nodejs=13
  - voila=0.1
  - ipyvolume=0.6.0a6
  - jupytext
  - ipython
  - networkx
  - netCDF4
  - cfunits
  - numpy
  - scikit-image
  - scipy
  - sympy
  - pandas
  - bqplot
  - notebook
  - ipycanvas
  - ipyevents
  - ipysheet
  - ipytree
  - ipympl
  - nbformat
  - ipyvuetify
  - voila-vuetify
  - ipywidgets
  - requests
  - pywwt
  - sidecar
  - ipyleaflet
  - pythreejs
  - pip
    #  - pip:
    #      - git+https://git@github.com/mamueller/testinfrastructure.git#egg=testinfrastructure 
    #      - git+https://git@github.com/MPIBGC-TEE/LAPM.git#egg=LAPM
    #      - git+https://git@github.com/MPIBGC-TEE/CompartmentalSystems.git#egg=CompartmentalSystems
    
