name: test_conda_developer_installation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        #python-version: [3.6,3.7, 3.8]

    steps:
    - name: Checkout submodules
      # You may pin to the exact commit or the version.
      # uses: textbook/git-checkout-submodule-action@0cb23c7e6a67085e1dc5e884920bd620f7b9c469
      uses: textbook/git-checkout-submodule-action@2.1.1
      with:
      # Set the --remote flag
        #remote: # optional
        repository: MPIBGC-TEE/bgc_md2
        token: ${{ secrets.ACCESS_TOKEN }}

    
    - name: Set up conda 
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: |
        which python
        python --version
    - name: Install dependencies
      run: |
        sudo chmod -R 777 . 
        ./install_developer_conda.sh

    - name: Test with unittest
      run: |
        cd tests
        python -m unittest discover -t . -p 'Test*'
        
        
