name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
        #python-version: [3.6,3.7, 3.8]

    steps:
    - uses: textbook/git-checkout-submodule-action@master
    - name: Set up conda 
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python
    - name: Install dependencies
      run: insta 
    - name: Lint with flake8
      run: ./install_developer_conda.sh
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        cd tests
        python -m unittest discover -t . -p 'Test*'
        
        
